baseurl = "https://tsako2235.github.io/blog"
languageCode = "ja"
title = "ぺけぺけ"
theme = "charaka"
copyright = "&copy; <a href=\"https://github.com/tsako2235\">tsako2235</a> 2018"
disqusShortname = ""
googleAnalytics = ""

[params]

[author]
  name = "tsako2235"
  homepage = "https://tsako2235.github.io/blog"

[params.highlight]
  style = "zenburn"

[params.share]
  enabled = "false"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info"

[[params.social]]
  url = "https://github.com/tsako2235/"
  fa_icon = "fab fa-github"

#[[params.social]]
#  url = "https://www.linkedin.com/in/natarajmb/"
#  fa_icon = "fab fa-linkedin-in"

[[params.social]]
  url = "https://twitter.com/c_takosa"
  fa_icon = "fab fa-twitter"
